const ENV_VAR = import.meta.env;

const APP_CONFIG = {
  MODE: ENV_VAR.MODE,

  API_KEY: ENV_VAR.VITE_API_KEY,
  APP_ID: ENV_VAR.VITE_APP_ID,
  AUTH_DOMAIN: ENV_VAR.VITE_AUTH_DOMAIN,
  MESSAGING_SENDER_ID: ENV_VAR.VITE_MESSAGING_SENDER_ID,
  PROJECT_ID: ENV_VAR.VITE_PROJECT_ID,
  STORAGE_BUCKET: ENV_VAR.VITE_STORAGE_BUCKET,
} as const;

export { APP_CONFIG };
